import React from 'react';
import { Canvas } from '@react-three/fiber';
import { OrbitControls, PerspectiveCamera, Grid, Text as DreiText } from '@react-three/drei';
import { useCardStore } from '../store';

const Card = () => {
  const { color, name, email, jobTitle, phoneNumber } = useCardStore();

  // Dimensions: 85mm x 54mm x 2mm
  // Scaled: 4.25 x 2.7 units

  // Text color based on card brightness could be calculated, but defaulting to white/black
  // For now using white with a slight shadow effect for visibility on most colors
  const textColor = '#FFFFFF';

  return (
    <mesh position={[0, -1.95, 0]}>
      <boxGeometry args={[4.25, 0.1, 2.7]} />
      <meshStandardMaterial
        color={color}
        roughness={0.3}
        metalness={0.1}
      />

      {/* Content Rendering - Local coords relative to mesh center */}
      {/* Surface is at y = 0.05. Placing text slightly above at y = 0.06 */}

      <group rotation={[-Math.PI / 2, 0, 0]} position={[0, 0.06, 0]}>
        {/* Name */}
        <DreiText
          position={[-1.8, -0.5, 0]} // Top leftish (in 2D generated by rotation)
          fontSize={0.25}
          color={textColor}
          anchorX="left"
          anchorY="top"
          maxWidth={3.8}
        >
          {name || 'Your Name'}
        </DreiText>

        {/* Job Title */}
        <DreiText
          position={[-1.8, -0.9, 0]}
          fontSize={0.15}
          color={textColor}
          anchorX="left"
          anchorY="top"
          maxWidth={3.8}
          fillOpacity={0.8}
        >
          {jobTitle || 'Job Title'}
        </DreiText>

        {/* Contact Info Group - Bottom Left */}
        <group position={[-1.8, 1.0, 0]}>
          <DreiText
            position={[0, 0, 0]}
            fontSize={0.12}
            color={textColor}
            anchorX="left"
            anchorY="bottom"
          >
            {phoneNumber || '(123) 456-7890'}
          </DreiText>
          <DreiText
            position={[0, 0.2, 0]}
            fontSize={0.12}
            color={textColor}
            anchorX="left"
            anchorY="bottom"
          >
            {email || 'email@example.com'}
          </DreiText>
        </group>
      </group>
    </mesh>
  );
};

export const ThreeScene: React.FC = () => {
  return (
    <div className="w-full h-full absolute inset-0">
      <Canvas>
        <PerspectiveCamera makeDefault position={[0, 2, 6]} fov={50} />
        <OrbitControls enablePan={false} maxPolarAngle={Math.PI / 1.5} target={[0, -2, 0]} />

        <ambientLight intensity={0.5} />
        <pointLight position={[10, 10, 10]} intensity={1} />
        <pointLight position={[-10, -10, -5]} intensity={0.5} color="#8FD9D9" />

        <Card />

        <Grid
          position={[0, -2, 0]}
          args={[20, 20]}
          cellColor="#8FD9D9"
          sectionColor="#8FD9D9"
          fadeDistance={15}
          fadeStrength={1}
          cellThickness={0.5}
          sectionThickness={1}
        />
      </Canvas>
    </div>
  );
};
